CREATE TABLE `SAPRELLO.USER` (
  `USER_ID` VARCHAR(10) PRIMARY KEY,
  `NAME` VARCHAR(50),
  `USERPASSWORD` VARCHAR(50),
  `EMAIL` VARCHAR(50),
  `IS_ADMIN` BOOLEAN(DEFAULT FALSE),
  `PROFILE_IMG` VARCHAR(255 DEFAULT SRC/ICON.JPG),
  `` <type>,
  `` <type>
);


CREATE TABLE `SAPRELLO.VOTES` (
  `{CARD_ID + USER_ID}` <type>,
  `INTEGER(DEFAULT 0)` <type>,
  `INTEGER(AI)` <type>,
  `VARCHAR(10)` <type>,
  KEY `VOTE_ID(PK)` (`{CARD_ID + USER_ID}`),
  KEY `AGREE_COUNT` (`INTEGER(DEFAULT 0)`),
  KEY `CARD_ID(FK)` (`INTEGER(AI)`),
  KEY `USER_ID(FK)` (`VARCHAR(10)`)
);



CREATE TABLE `SAPRELLO.BOARD` (
  `BOARD_ID(PK)` INTEGER(AI),
  `BOARD_TITLE` VARCHAR(255),
  `BOARD_DESCRIPTION` VARCHAR(1000)
);

CREATE TABLE `SAPRELLO.CARD` (
  `CARD_ID (PK)` INTEGER (AI),
  `DATE_ADDED` DATE(DEFAULT CURRENT_DATE),
  `TITLE` VARCHAR(255),
  `DESCRIPTION` VARCHAR(1000),
  `CARD_STATUS` VARCHAR (IN 'GLAD', 'MAD', 'SAD'),
  `BOARD_ID(FK)` INTEGER,
  `USER_ID(FK)` VARCHAR(10)
);

CREATE TABLE `SAPRELLO.SUBSCRIBED` (
  `VARCHAR(10)` <type>,
  `INTEGER` <type>,
  `BOOLEAN(DEFAULT TRUE)` <type>,
  KEY `USER_ID(FK)` (`VARCHAR(10)`),
  KEY `BOARD_ID(FK)` (`INTEGER`),
  KEY `BOARD_DISPLAY` (`BOOLEAN(DEFAULT TRUE)`)
);
